### PR TITLE
Update MangaRock.pas

### PR DESCRIPTION
**Pull request by kevin01523**
update fix api

https://github.com/riderkick/FMD/issues/1545

#1545

### CODE REVIEW

**Comment by TIAIAN** [comment]
how to i add it or change it in FMD or the FMD folder, can you show it.

**Comment by kevin01523** [comment]
> how to i add it or change it in FMD or the FMD folder, can you show it.

you have to recompile FMD 
there is a tutorial or short instruction on how to compile FMD on FMD project root directory or the readme.md file

**Comment by TIAIAN** [comment]
i tried building/compiling FMD, but it got very confusing so can you create a video tutorial to show how to do it or share your edited FMD like traitorAIZEN said?

**Comment by Shinihime** [comment]
As I couldn't get this project to compile I just opened fmd.exe with a hex-editor and searched for "web400" (3 times in there), replaced it with "web401" and mangarock works again.

**Comment by TIAIAN** [comment]
whats a hex-editor?

**Comment by TIAIAN** [comment]
> whats a hex-editor?

never mind, i just searched it up, downloaded it, find and replaced web400 with web401 and it works now. Thank you Shinihime

**Comment by Appolosandal** [comment]
Excuse me to bother. I am new to programming and i don't know even single piece of it. May you tell what is web400?

**Comment by Shinihime** [comment]
If you click on "Commits" then on "Update MangaRock.pas then you'll see changed source code.
old:  if DownloadThread.FHTTP.GET(ModuleApiUrl + '/query/web400/pages?oid=' + chapterId) then
new:  if DownloadThread.FHTTP.GET(ModuleApiUrl + '/query/web401/pages?oid=' + chapterId) then

If you open fmd.exe with a hex-editor you can search for that text "web400", replace it with "web401" (3 times) and save those changes. After that it's working again for MangaRock.

**Pull request merged**
